apiVersion: v1
kind: ConfigMap
metadata:
  name: shipment-config
  namespace: shipment-tracker
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "shipment_db"
  REDIS_URL: "redis://redis-service:6379/0"
  RABBITMQ_URL: "amqp://shipment_user:shipment_pass@rabbitmq-service:5672/"
  ELASTICSEARCH_HOST: "http://elasticsearch-service:9200"
  DEBUG: "False"